stages:
  # - test
  - deploy

# test:
#   stage: test
#   script:
#   - apt-get update -qy
#   - apt-get install -y python-dev python-pip
#   - pip install pipenv
#   - pipenv install --ignore-pipfile
#   - pipenv run pytest

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=lurker --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags